# Generated by Django 5.2.12 on 2026-04-05 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticity_status',
            field=models.CharField(choices=[('seller_declared', 'Seller Declared'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified')], default='seller_declared', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('gently_used', 'Gently Used'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('vintage', 'Vintage')], default='gently_used', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='condition_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='escrow_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_purchase_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='resale_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archived', 'Archived')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_from',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
