# Generated by Django 5.2.13 on 2026-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_authenticity_status_product_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
