# Generated by Django 5.2.12 on 2026-04-05 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('payout_email', models.EmailField(blank=True, max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('seller_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('escrow_policy', models.CharField(default='Funds stay protected until the buyer confirms the item matches the listing.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
    ]
