# Generated by Django 5.2.13 on 2026-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
