# Generated by Django 5.2.13 on 2026-04-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sellerprofile_account_holder_name_and_more'),
        ('accounts', '0006_sellerrating'),
    ]

    operations = [
    ]
