# Generated by Django 5.2.12 on 2026-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_seller_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cashfree_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
