# Generated by Django 5.2.13 on 2026-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_masterpayment_order_master_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='payout_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='payout_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
